### ISSUE TITLE
Add Travis CI

### ISSUE THREAD

**Issue by StefanoMagrassi** [contactlab/shipit-clab-deploy#1]
Add Travis CI with `.travis.yml` file:

```yaml
language: node_js
node_js:
  - "8"
  - "node"
```
